### ISSUE TITLE
[Improvement] Updating translation PT-BR

### ISSUE THREAD

**Issue by Myiamoto86** [loki79uk/FS22_TipAnywhere#6]
Loki,

Good morning.
[l10n_br.txt](https://github.com/loki79uk/FS22_TipAnywhere/files/11767322/l10n_br.txt)
[modDesc.txt](https://github.com/loki79uk/FS22_TipAnywhere/files/11767323/modDesc.txt)

How are you my friend? I hope you are well.

Here is the update for the PT-BR translation.

One more detail... Congratulations. Great job.

**Comment by loki79uk** [comment]
Thanks for the translation!  Added in [this commit](https://github.com/loki79uk/FS22_TipAnywhere/commit/d42550fb847017e0cac6bb8e5455cd19b3650fd0), it will be included in the next release.
